//
//  HelloWorldPresenter.swift
//  BMantzeyPortfolio
//
//  Created by Brandon Mantzey on 10/29/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HelloWorldPresentationLogic
{
  func presentTestText(response: HelloWorld.Something.Response)
}

class HelloWorldPresenter: HelloWorldPresentationLogic
{
  weak var viewController: HelloWorldDisplayLogic?
  
  // MARK: Do something
  
  func presentTestText(response: HelloWorld.Something.Response)
  {
      let viewModel = HelloWorld.Something.ViewModel(displayText: response.displayText)
    viewController?.displayTestText(viewModel: viewModel)
  }
}
