//
//  HelloWorldInteractor.swift
//  BMantzeyPortfolio
//
//  Created by Brandon Mantzey on 10/29/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HelloWorldBusinessLogic {
  func showDisplayText(request: HelloWorld.Something.Request)
}

protocol HelloWorldDataStore
{
  //var name: String { get set }
}

class HelloWorldInteractor: HelloWorldBusinessLogic, HelloWorldDataStore
{
  var presenter: HelloWorldPresentationLogic?
  var worker: HelloWorldWorker?
  //var name: String = ""
  
  // MARK: Do something
    func showDisplayText(request: HelloWorld.Something.Request) {
    worker = HelloWorldWorker()
    let displayText = worker?.getDisplayText()
    
        let response = HelloWorld.Something.Response(displayText: displayText ?? "")
        presenter?.presentTestText(response: response)
  }
}
