//
//  HelloWorldRouter.swift
//  BMantzeyPortfolio
//
//  Created by Brandon Mantzey on 10/29/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HelloWorldRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol HelloWorldDataPassing
{
  var dataStore: HelloWorldDataStore? { get }
}

class HelloWorldRouter: NSObject, HelloWorldRoutingLogic, HelloWorldDataPassing
{
  weak var viewController: HelloWorldViewController?
  var dataStore: HelloWorldDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: HelloWorldViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: HelloWorldDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
